# Generated by Django 3.2.9 on 2021-11-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='miniature',
            field=models.ImageField(null=True, upload_to='posts/images/'),
        ),
    ]
